// src/components/DeleteAction.svelte
<script lang="ts">
    import { fetchAuthorized } from "@/lib/api";
    import { invalidate } from '$app/navigation';
    import { Button } from "flowbite-svelte";
    import Trash from "phosphor-svelte/lib/Trash";

    export let assetId: string;
    export let trackId: string;

    let isDeleted = false;

    const deleteTrack = async () => {
        isDeleted = true;

        await fetchAuthorized(
            `/api/assets/${ assetId }/tracks/${ trackId }`,
            {
                method: 'DELETE'
            }
        );
        await invalidate(
            `/api/assets/${ assetId }`
        );
    };
</script>

<Button
    on:click={ deleteTrack }
    disabled={ isDeleted }
    color="red"
>
    { #if !isDeleted }
        Delete
    { :else }
        Deleted
    { /if }
    <Trash />
</Button>

// components/DeleteAction.tsx
import { fetchAuthorized } from "@/app/util";
import { mutate } from "swr";
import { Button } from "@chakra-ui/react";
import { useCallback } from "react";
import { PiTrash } from "react-icons/pi";

interface Props {
    assetId: string,
    trackId: string
}

export const DeleteAction = (props: Props) => {
    const { assetId, trackId } = props;

    const deleteTrack = useCallback(async () => {
        await fetchAuthorized(`/api/assets/${ assetId }/tracks/${ trackId }`, {
            method: 'DELETE'
        });
        mutate(`/api/assets/${ assetId }`);
    }, []);

    return (
        <Button onClick={ deleteTrack } colorScheme="red">
            Delete <PiTrash />
        </Button>
    );
};

export default DeleteAction;
