// src/components/TrackDetails.svelte
<script lang="ts">
    import type Mux from "@mux/mux-node";
    import { AccordionItem } from "flowbite-svelte";
    import DownloadAction from "@/components/DownloadAction.svelte";
    import DeleteAction from "@/components/DeleteAction.svelte";
    import VideoCamera from "phosphor-svelte/lib/VideoCamera";
    import MusicNotes from "phosphor-svelte/lib/MusicNotes";
    import Subtitles from "phosphor-svelte/lib/Subtitles";

    export let assetId: string;
    export let playbackId: string;
    export let track: Mux.Video.Track;

    const isGenerated = track.type == "text" &&
        track.text_source?.startsWith("generated");
    const isDeletable = track.type == "text" ||
        (track.type == "audio" && !track.primary);
    const isDownloadable = track.type == "text" &&
        track.status == "ready";
</script>

<AccordionItem tag="div">
    <span class="track-details__disclosure" slot="header">
        { #if track.type == "video" }
            <VideoCamera />
        { :else if track.type == "audio" }
            <MusicNotes />
        { :else if track.type == "text" }
            <Subtitles />
        { /if }
        { track.type }
        { #if isGenerated }
            (autogen)
        { /if }
    </span>
    <code>
        { JSON.stringify(track) }
    </code>
    { #if isDownloadable && track.id }
        <DownloadAction
            playbackId={ playbackId }
            trackId={ track.id }
        />
    { /if }
    { #if isDeletable && track.id }
        <DeleteAction
            assetId={ assetId }
            trackId={ track.id }
        />
    { /if }
</AccordionItem>
<style>
    .track-details__disclosure {
        display: inline-flex;
        align-items: center;
        gap: 0.5em;
    }
</style>

// components/TrackDetails.tsx
import type Mux from "@mux/mux-node";
import { AccordionItem, AccordionButton, AccordionPanel, AccordionIcon } from "@chakra-ui/react";
import DeleteAction from "./DeleteAction";
import DownloadAction from "./DownloadAction";
import { PiMusicNotes, PiSubtitles, PiVideoCamera } from "react-icons/pi";
import styles from "../styles/components/TrackDetails.module.css";

interface Props {
    assetId: string,
    playbackId: string,
    track: Mux.Video.Track
}

export const TrackDetails = (props: Props) => {
    const { assetId, playbackId, track } = props;

    if (!track.id) { return; }

    const isGenerated = track.type == "text" &&
        track.text_source?.startsWith("generated");
    const isDeletable = track.type == "text" ||
        (track.type == "audio" && !track.primary);
    const isDownloadable = track.type == "text" &&
        track.status == "ready";

    return (
        <AccordionItem>
            <AccordionButton className={ styles['track-details__disclosure'] }>
                <span className={ styles['track-details__type'] }>
                    { track.type == "video" ? (
                        <PiVideoCamera />
                    ) : track.type == "audio" ? (
                        <PiMusicNotes />
                    ) : (
                        <PiSubtitles />
                    ) }
                    { track.type }
                    { isGenerated && ' (autogen)' }
                </span>
                <AccordionIcon />
            </AccordionButton>
            <AccordionPanel>
                { JSON.stringify(track) }
                { isDownloadable && (
                    <DownloadAction
                        playbackId={ playbackId }
                        trackId={ track.id }
                    />
                ) }
                { isDeletable && (
                    <DeleteAction
                        assetId={ assetId }
                        trackId={ track.id }
                    />
                ) }
            </AccordionPanel>
        </AccordionItem>
    );
};

export default TrackDetails;
