// src/components/UploadAction.svelte
<script lang="ts">
    import { Button, Modal, Fileupload } from "flowbite-svelte";
    import Upload from "phosphor-svelte/lib/Upload";
    import { fetchAuthorized } from "@/lib/api";
    import { invalidate } from '$app/navigation';

    export let assetId: string;

    let isOpen = false;
    let files: FileList;

    const uploadFile = async () => {
        if (files.length != 1) {
            return;
        }

        const formData = new FormData();
        formData.append("file", files[0]);

        await fetchAuthorized(
            `/api/assets/${ assetId }/tracks`,
            {
                method: 'POST',
                body: formData
            }
        );
        await invalidate(
            `/api/assets/${ assetId }`
        );
    };
</script>

<Button on:click={ () => { isOpen = true } }>
    Upload <Upload />
</Button>
<Modal
    title="Upload"
    bind:open={ isOpen }
    autoclose
>
    <Fileupload
        id="file-upload"
        accept=".vtt,.srt"
        bind:files
        required
    />
    <p>Allowed file types: .vtt, .srt</p>
    <svelte:fragment slot="footer">
        <Button on:click={ uploadFile }>
            Upload
        </Button>
    </svelte:fragment>
</Modal>

// components/UploadAction.tsx
import { useCallback } from "react";
import { Modal, ModalBody, ModalFooter, ModalHeader, ModalContent, ModalOverlay, Button, useDisclosure } from "@chakra-ui/react";
import { PiUpload } from "react-icons/pi";
import FileDropzone from "./FileDropzone";
import { fetchAuthorized } from "@/app/util";

interface Props {
    assetId: string
}

export const UploadAction = (props: Props) => {
    const { assetId } = props;

    const { isOpen, onOpen, onClose } = useDisclosure();

    const uploadFile = useCallback((file: File) => {
        const formData = new FormData();
        formData.append('file', file);

        fetchAuthorized(`/api/assets/${ assetId }/tracks`, {
            method: 'POST',
            body: formData
        });
    }, [ assetId ]);

    return (
        <>
            <Button onClick={ onOpen }>
                Upload <PiUpload />
            </Button>
            <Modal
                isOpen={ isOpen }
                onClose={ onClose }
            >
                <ModalOverlay>
                    <ModalContent>
                        <ModalHeader>
                            Upload
                        </ModalHeader>

                        <ModalBody>
                            <FileDropzone onChange={ uploadFile } />
                        </ModalBody>

                        <ModalFooter>
                            <Button>
                                Done
                            </Button>
                        </ModalFooter>
                    </ModalContent>
                </ModalOverlay>
            </Modal>
        </>
    )
};

export default UploadAction;
